/**
 * Build-time country narrative generator.
 *
 * Reads rankings + evidence, builds fact bundles, then:
 *   1. Deterministic slot narratives (always)
 *   2. OpenAI prose (when OPENAI_API_KEY is set and validation passes)
 *
 * Outputs:
 *   src/data/2026/generated/country-narratives.generated.json
 *   src/data/2026/generated/country-narrative-facts.json
 *   docs/country-narratives-index.md
 *
 * Run:
 *   pnpm build:narratives                    # auto: LLM if OPENAI_API_KEY set, else deterministic
 *   pnpm build:narratives:llm                # force LLM (reads .env.local)
 *   pnpm build:narratives:deterministic      # force deterministic (no API calls)
 *   NARRATIVE_SOURCE=llm pnpm build:narratives
 *
 * Loads `.env.local` and `.env` from the repo root (shell env wins).
 * Requires prior: pnpm build:data
 */

import fs from "node:fs";
import path from "node:path";
import rankingsData from "../src/data/2026/generated/rankings.json";
import evidenceData from "../src/data/2026/generated/evidence.json";
import pillarHighlightsData from "../src/data/2026/generated/country-pillar-highlights.json";
import { DIMENSIONS, PILLARS } from "../src/data/2026/taxonomy";
import { buildAllCountryFactBundles } from "../src/lib/country-narratives/facts";
import { buildAllDeterministicNarratives } from "../src/lib/country-narratives/deterministic";
import {
  NARRATIVE_SCHEMA_VERSION,
  type CountryNarrativeFactsArtifact,
  type CountryNarrativesArtifact,
} from "../src/lib/country-narratives/types";
import type {
  CountryPillarHighlightsArtifact,
  EvidenceArtifact,
  RankingsArtifact,
} from "../src/lib/girai/types";
import {
  generateCountryNarrativesWithLlm,
  getOpenAiModel,
  validateLlmNarratives,
} from "./lib/narrative-llm";
import { loadEnvFiles, resolveNarrativeBuildMode } from "./lib/load-env";

const ROOT = path.resolve(__dirname, "..");
loadEnvFiles(ROOT);
const OUT_DIR = path.join(ROOT, "src/data/2026/generated");
const DOCS_INDEX = path.join(ROOT, "docs/country-narratives-index.md");

const rankings = rankingsData as unknown as RankingsArtifact;
const evidence = evidenceData as unknown as EvidenceArtifact;
const pillarHighlights =
  pillarHighlightsData as unknown as CountryPillarHighlightsArtifact;

function writeJson(filePath: string, data: unknown) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function writeDocsIndex(
  artifact: CountryNarrativesArtifact,
  factsCount: number
) {
  const lines = [
    "# Country narratives index",
    "",
    "Auto-generated by `pnpm build:narratives`. Editorial copy for country pages is grounded in the 2026 dataset fact bundles — not score-tier templates.",
    "",
    "## Build metadata",
    "",
    `| Field | Value |`,
    `|-------|-------|`,
    `| Schema | ${artifact.schemaVersion} |`,
    `| Generated at | ${artifact.generatedAt} |`,
    `| Dataset hash | \`${artifact.sourceHash}\` |`,
    `| Narrative source | **${artifact.source}** |`,
    `| LLM model | ${artifact.model ?? "—"} |`,
    `| Countries | ${factsCount} |`,
    "",
    "## Regeneration",
    "",
    "```bash",
    "pnpm build:data                    # refresh scores and evidence first",
    "pnpm build:narratives:llm          # force LLM (uses OPENAI_API_KEY from .env.local)",
    "pnpm build:narratives:deterministic # force slot-based copy, no API calls",
    "pnpm build:narratives              # auto: LLM if key present, else deterministic",
    "```",
    "",
    "Set `NARRATIVE_SOURCE=llm|deterministic|auto` or pass `--llm` / `--deterministic`.",
    "Place `OPENAI_API_KEY` in `.env.local` (loaded automatically; not committed).",
    "",
    "## Country index",
    "",
    "| ISO3 | Country | Global rank | GIRAI | Source |",
    "|------|---------|-------------|-------|--------|",
  ];

  const sorted = [...rankings.countries].sort((a, b) => {
    const ra = a.rankGlobal ?? 9999;
    const rb = b.rankGlobal ?? 9999;
    return ra - rb;
  });

  for (const c of sorted) {
    const hasNarrative = artifact.countries[c.iso3]?.hero;
    if (!hasNarrative) continue;
    lines.push(
      `| ${c.iso3} | ${c.name} | ${c.rankGlobal ?? "—"} | ${c.girai?.toFixed(1) ?? "—"} | ${artifact.source} |`
    );
  }

  lines.push(
    "",
    "## Pilot examples (review copy)",
    "",
    "See [country-narratives.md](./country-narratives.md) for methodology. Compare Brazil and Singapore in the fact-bundle examples section.",
    "",
    `*Last built: ${artifact.generatedAt}*`,
    ""
  );

  fs.writeFileSync(DOCS_INDEX, lines.join("\n"), "utf8");
}

async function main() {
  const generatedAt = new Date().toISOString();
  const sourceHash = rankings.sourceHash;

  const factBundles = buildAllCountryFactBundles({
    countries: rankings.countries,
    evidenceItems: evidence.items,
    pillarHighlights: pillarHighlights.countries,
  });

  const deterministic = buildAllDeterministicNarratives(factBundles);
  let finalNarratives = deterministic;
  let source: CountryNarrativesArtifact["source"] = "deterministic";
  let model: string | null = null;

  const mode = resolveNarrativeBuildMode(process.argv.slice(2));
  const apiKey = process.env.OPENAI_API_KEY?.trim();
  const useLlm =
    mode === "llm" || (mode === "auto" && Boolean(apiKey));

  if (mode === "llm" && !apiKey) {
    console.error(
      "[build:narratives] NARRATIVE_SOURCE=llm (or --llm) but OPENAI_API_KEY is not set. Add it to .env.local or the shell environment."
    );
    process.exit(1);
  }

  if (mode === "deterministic") {
    console.log("[build:narratives] Mode: deterministic (forced).");
  } else if (useLlm) {
    model = getOpenAiModel();
    console.log(
      `[build:narratives] Mode: ${mode === "auto" ? "auto → llm" : "llm"} (${model})…`
    );
    const llmOut = { ...deterministic };
    let llmCount = 0;
    let failCount = 0;
    const isos = Object.keys(factBundles).sort();

    for (const iso of isos) {
      const bundle = factBundles[iso]!;
      try {
        const llm = await generateCountryNarrativesWithLlm(bundle, apiKey!);
        const errors = validateLlmNarratives(bundle, llm);
        if (errors.length > 0) {
          console.warn(`[build:narratives] ${iso} validation failed: ${errors.join("; ")}`);
          failCount++;
        } else {
          llmOut[iso] = llm;
          llmCount++;
        }
      } catch (err) {
        console.warn(
          `[build:narratives] ${iso} LLM error:`,
          err instanceof Error ? err.message : err
        );
        failCount++;
      }
      await sleep(150);
    }

    console.log(
      `[build:narratives] LLM: ${llmCount} ok, ${failCount} fell back to deterministic`
    );
    if (llmCount > 0) {
      finalNarratives = llmOut;
      source = "generated";
    }
  } else {
    console.log(
      "[build:narratives] Mode: auto → deterministic (OPENAI_API_KEY not set)."
    );
  }

  const narrativesArtifact: CountryNarrativesArtifact = {
    schemaVersion: NARRATIVE_SCHEMA_VERSION,
    generatedAt,
    sourceHash,
    source,
    model,
    countries: finalNarratives,
  };

  const factsArtifact: CountryNarrativeFactsArtifact = {
    schemaVersion: NARRATIVE_SCHEMA_VERSION,
    generatedAt,
    sourceHash,
    countries: factBundles,
  };

  writeJson(path.join(OUT_DIR, "country-narratives.generated.json"), narrativesArtifact);
  writeJson(path.join(OUT_DIR, "country-narrative-facts.json"), factsArtifact);
  writeDocsIndex(narrativesArtifact, Object.keys(factBundles).length);

  console.log(
    `[build:narratives] Wrote ${Object.keys(finalNarratives).length} countries (${source})`
  );
}

main().catch((err) => {
  console.error("[build:narratives] Failed:", err);
  process.exit(1);
});
